SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Employee3_v2](
	[No] [int] NOT NULL,
	[Name] [nchar](15) NOT NULL,
	[RegDate] [date] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Employee3_v2] ADD  CONSTRAINT [PK_Employee3] PRIMARY KEY CLUSTERED 
(
	[No] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
